### ISSUE TITLE
Babel and AST - reg exp variableDeclarator

### ISSUE THREAD

**Issue by jakubsadura** [kentcdodds/asts-workshop#13]
In the video that introduces Babel and AST it is suggested to use `t.variableDeclarator(newIdentifier, path.node)`, my initial idea was to do `t.variableDeclarator(newIdentifier, t.regExpLiteral(path.node.pattern, path.node.flags))` instead. This would fail with following error:

```
TypeError: unknown: undefined is not an object (evaluating 'n.extra.raw')
genericPrintNoParens — 8-b12b22d8d7b33937e14f-12.js:1587:8752
genericPrint — 8-b12b22d8d7b33937e14f-12.js:1587:1349
r — 8-b12b22d8d7b33937e14f-12.js:1587:582
n — 8-b12b22d8d7b33937e14f-12.js:1587:522
a — 8-b12b22d8d7b33937e14f-12.js:1587:449
printComments — 8-b12b22d8d7b33937e14f-12.js:2133:3525
t — 8-b12b22d8d7b33937e14f-12.js:1587:220
call — 8-b12b22d8d7b33937e14f-12.js:4811:1780
```

Do you have idea why this would not work?
According to docs `t.regExpLiteral(pattern, flags)` should be ok

My babel plugin code:
```
export default function (babel) {
  const { types: t } = babel;
  
  return {
    name: "regexHoister", // not required
    visitor: {
      RegExpLiteral(path) {
        const oldName = path.parent.id.name;
        const newIdentifier = path.scope.generateUidIdentifier(oldName);
        //const hoistedVar = t.variableDeclarator(newIdentifier, path.node);
        const hoistedVar = t.variableDeclarator(newIdentifier, t.regExpLiteral(path.node.pattern, path.node.flags));
        const varDeclaration = t.variableDeclaration('const', [hoistedVar]);
        const program = path.findParent(t.isProgram);

        
        path.scope.rename(oldName, newIdentifier.name)
        program.node.body.unshift(varDeclaration)
        path.parentPath.remove()
      }
    }
  };
}
```

**Comment by kentcdodds** [comment]
Hi there!

I'm not sure... Lots of this stuff is still a bit of a mystery to me. There's a lot to know! My guess is it could be due to the fact that you're removing the parent node so those nodes are somehow disconnected or something. But yeah, it's hard to tell. Sorry I couldn't be more helpful. Good luck though!

**Comment by jakubsadura** [comment]
I checked and it is not due to removing, anyway thanks for your reply :) It's great to hear from you and know that you care so much! Best of luck to you and looking forward to your future courses on Frontend Masters 💯

**Comment by jakubsadura** [comment]
@kentcdodds I've just finished watching this course, it's really awesome. I even published my eslint plugin https://github.com/jakubsadura/eslint-plugin-no-shit that will check if codebase is clean from offensive language, couldn't find anything similar in the opensource.  Kudos goes to you! Looking forward for more courses from you 🎱

**Comment by kentcdodds** [comment]
Dude, I love that! Sounds like the project couldn't pass it's own rules though 😉

**Comment by jakubsadura** [comment]
It's really simple plugin but if someone starts using it I see no problem improving it (keeping in mind that some offensive words might be part of non-offensive ones - like `class`). This is my first npm package ever - do you know if there is any way to advertise it?

Regards

**Comment by kentcdodds** [comment]
There's not really an official way to advertise things. I pretty much just tweet about it. But I'm a bit privileged because I have a pretty good following. You might also consider reaching out to relevant newsletter curators who could get your thing out to a bigger audience.

Note, I did actually tweet about your project here: https://twitter.com/kentcdodds/status/909914427419385856 :smile:

**Comment by jakubsadura** [comment]
Thank you!!!
