### ISSUE TITLE
Node version issue when setting up

### ISSUE THREAD

**Issue by harmeetjaipur** [kentcdodds/asts-workshop#15]
Hi,

I looked at the preview for your ast course and it made me signup for frontendmasters' account. I am trying to setup ast project and I get following error when I run 'yarn run setup --silent':

`You must have node version 6 installed.`

I have node v10.9.0 installed. Any ideas?

**Comment by harmeetjaipur** [comment]
Nm, `npm i` did the job.

**Comment by kentcdodds** [comment]
Woo! Thanks :)
