### ISSUE TITLE
verify requires yarn

### ISSUE THREAD

**Issue by tomByrer** [kentcdodds/asts-workshop#8]
```
λ node ./scripts/verify
'yarn' is not recognized as an internal or external command,
```

`npm run setup` seems to work; tests passed!

Yarn does not work on my Windows10 system.  Could be a combo of PATHs & ConEmu, but I'm not going to take the time to mess with that beta software.

**Comment by kentcdodds** [comment]
You can feel free to continue the workshop without using yarn. Just know that without the benefit of the `yarn.lock` file, transitive dependencies can change from the original workshop and you may end up with surprising results.

From [the README](https://github.com/kentcdodds/asts-workshop#note-on-yarn):

> If you don't have yarn installed and don't want to use it for some reason, you can use npm as well. Instead of `yarn start setup`, run `node ./scripts/install && npm start validate` and enjoy waiting (and hopefully things don't break for you). May be a good idea to still run `node ./scripts/verify` to verify you have the right version of other things too.

Good luck to you!

**Comment by tomByrer** [comment]
Thanks for your fast reply!

Understood, FYI NPM 5, releasing later this week [will have `npm-shrinkwrap.json` ](https://github.com/npm/npm/pull/16244) & slightly faster caching.
