### ISSUE TITLE
Extend ex.es.5's final solution

### ISSUE THREAD

**Issue by mstaicu** [kentcdodds/asts-workshop#9]
Hello ✋🏻, I'm trying to make a PR to present to you an extended solution on the fifth ESLint exercise, but I can't seem to understand how exactly ```split-guide``` works. I've created the (with the ```split-guide``` markup) exercise file and its test file inside the ```templates``` directory (which is on the root of the project) and I've issued ```yarn start split``` but nothing happens, nothing updates on the file system, even though I get this output:

```javascript
yarn start v0.27.5
$ nps "split"
nps is executing `split` : node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "split.exercises,split.demos" 'nps split.exercises' 'nps split.demos'
[split.exercises] nps is executing `split.exercises` : split-guide generate --templates-dir other/old-exercises/templates --exercises-dir other/old-exercises/exercises --exercises-final-dir other/old-exercises/exercises-final --silent-success
[split.demos] nps is executing `split.demos` : split-guide generate --templates-dir other/old-demos/templates --exercises-dir other/old-demos/start --exercises-final-dir other/old-demos/final --silent-success
[split.demos] nps split.demos exited with code 0
[split.exercises] nps split.exercises exited with code 0
Done in 2.31s.
```
What am I doing wrong?

**Comment by kentcdodds** [comment]
Hi! Thanks for your help!

Sorry about that. That's outdated info in the CONTRIBUTING.md file. 😱 I _used_ to use `split-guide` but I dropped that in favor of a simpler experience for workshop attendees. I've updated the CONTRIBUTING.md which illustrates the right way to do things now. Sorry about that!

**Comment by mstaicu** [comment]
Not a problem. There's one more catch though. I went in and modified the ```other/final/``` files directly. However, if I run ```npm start exercise.eslint.4```, for example, it will copy the ```no-console.test.js``` from exercise 5 and the ```no-console.js``` from exercise 4. Is this the correct behavior? This would be my last question before creating the PR.

**Comment by kentcdodds** [comment]
Yes, that is correct, because the attendee is supposed to write the code to make the tests pass 👍

**Comment by mstaicu** [comment]
So, I've created a PR [here](https://github.com/kentcdodds/asts-workshop/pull/10). If this is not desired, let me know. I was doing your workshop on FEM and I thought that it would be cool to go on my own and learn some things and maybe do a PR while doing it. PS, it's my first, so I'm still not sure if I followed the exact protocol.
